export const LOGIN_ACTION = "LOGIN_ACTION";
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_LOCATION = "LOGIN_ACTION"; 
export const UPDATE_OPERATIONS = "UPDATE_OPERATIONS";
export const UPDATE_OPERATIONS_TIME = "UPDATE_OPERATIONS_TIME";
export const UPDATE_LASTPAGE_OF_OPERATION = "UPDATE_LASTPAGE_OF_OPERATION";
export const UPDATE_TASK = "UPDATE_TASK";
